### ISSUE TITLE
hotfixv4.trafficmanager.net dont work

### ISSUE THREAD

**Issue by anjia0532** [jborean93/ansible-windows#14]
```
详细信息: downloading url
'https://hotfixv4.trafficmanager.net/Windows%207/Windows%20Server2008%20R2%20SP1/sp2/Fix467402/7600/free/463984_intl_x6
4_zip.exe' to 'C:\Users\ADMINI~1\AppData\Local\Temp\1\463984_intl_x64_zip.exe.zip'
C:\Users\Administrator\AppData\Local\Temp\1\Install-WMF3Hotfix.ps1 : 使用“2”个参数调用“DownloadFile”时发生异常:“Un
able to connect to the remote server”
    + CategoryInfo          : NotSpecified: (:) [Install-WMF3Hotfix.ps1], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Install-WMF3Hotfix.ps1
```

`https://hotfixv4.trafficmanager.net` and `http://hotfixv4.microsoft.com` both of down
> I think it might be better advice to suggest updating to WMF 4.0 which is available from Windows 7 /Server 2008 R2 onwards.

ref https://github.com/ansible/ansible/issues/10825#issuecomment-95810501

**Comment by jborean93** [comment]
I've fixed the URLs with https://github.com/jborean93/ansible-windows/commit/d000c48879c984928a50ff0ed5936737cc4f897d. They are now pointing to an S3 bucket in Ansible that is used for their CI testing so will hopefully be a bit more stable. Unfortunately there are still no guarantees for this to stay active but it should get us going for now. Server 2008 and 2008 R2 are end of life at the start of next year so this should be less of an issue going forward.

> I think it might be better advice to suggest updating to WMF 4.0 which is available from Windows 7 /Server 2008 R2 onwards.

In reality they should be installing WMF 5.1 and just skip 4.0. 5.1 adds a lot more features around logging and other useful stuff that it's highly recommended to just upgrade. Unfortunately not every organisation has that luxury.

**Comment by anjia0532** [comment]
@jborean93 thanks for your reply.

In my test, 2008 R2 SP1 and Win7 support WMF 5.1. it works. thanks again.

>Installation of WMF 5.1 on either Windows Server 2008 R2 SP1 or Windows 7 SP1, requires the following:

>Latest service pack must be installed.
> - WMF 3.0 must not be installed. Installing WMF 5.1 over WMF 3.0 will result in the loss of the PSModulePath, which can cause other applications to fail. Before installing WMF 5.1, you must either un-install WMF 3.0, or save the PSModulePath and then restore it manually after WMF 5.1 installation is complete.
> - WMF 5.1 requires at least .NET Framework 4.5.2. You can install Microsoft .NET Framework 4.5.2 by following the instructions at the download location.

[Install and Configure WMF 5.1](https://docs.microsoft.com/en-us/powershell/wmf/5.1/install-configure)

**Comment by jborean93** [comment]
As a side note, you can also use https://github.com/jborean93/ansible-windows/blob/master/scripts/Upgrade-PowerShell.ps1 to do the update to 5.1.

**Comment by anjia0532** [comment]
yes , [from ansible doc](https://docs.ansible.com/ansible/latest/user_guide/windows_setup.html#upgrading-powershell-and-net-framework)
