### ISSUE TITLE
Unable to install Google Chrome on an windows host(I am getting the following error)

### ISSUE THREAD

**Issue by DipanjanSG** [jborean93/ansible-windows#15]
failed: [10.64.14.11] (item=-"googlechrome") => {"changed": false, "item": "-\"googlechrome\"", "module_stderr": "An error occurred while creating the pipeline.\r\n    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordE \r\n   xception\r\n    + FullyQualifiedErrorId : RuntimeException\r\n \r\n\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 2}

**Comment by DipanjanSG** [comment]
@jborean93 Can You kindly look into the issue

**Comment by jborean93** [comment]
This is a know issue with the latest chocolatey version, a quick google search will bring up numerous pages.
