### ISSUE TITLE
PSScriptInfo being read on WinServer 2008 Standard SP2

### ISSUE THREAD

**Issue by dandoingdev** [jborean93/ansible-windows#2]
The comment block <#PSScriptInfo is being treated as script content on Powershell 1.0, is there an easy fix for this?

**Comment by jborean93** [comment]
hmm looks like only `#` are viewed as comments on PS v1, will probably just have to remove the text until I find a better solution.

**Comment by jborean93** [comment]
This was fixed with https://github.com/jborean93/ansible-windows/commit/57bd33aca8816246894e15232751b6ee27200956
