### ISSUE TITLE
Udpate fedora 27 to fedora 28

### ISSUE THREAD

**Issue by Daniel-Sanchez-Fabregas** [jborean93/ansible-windows#7]
Should be possible to update to fedora 28 in inventory?

https://github.com/jborean93/ansible-windows/blob/2225681acbb33a6a84e2b0af54126985856dcbda/vagrant-linux/inventory.yml#L14-L16

**Comment by jborean93** [comment]
I don't see why not, feel free to send through a PR.

**Comment by jborean93** [comment]
Thanks, updated with https://github.com/jborean93/ansible-windows/pull/10
