### ISSUE TITLE
Upgrade-PowerShell.ps1 and Server 2012 R2

### ISSUE THREAD

**Issue by mdeveric** [jborean93/ansible-windows#8]
Hi there,

Great Script but in testing it incorrectly identifies Server 2012 R2 as Server 2012. The minor version in Server 2012 R2 is still 2 so it will download the file W2K12-KB3191565-x64.msu where it should get Win8.1AndW2K12R2-KB3191564-x64.msu

Cheers

Matt

**Comment by jborean93** [comment]
Thanks, I went a slightly different route as part of https://github.com/jborean93/ansible-windows/pull/10 but it achieves the same results.
