### ISSUE TITLE
A part of the code is deprecated on windows 8.1, runs but with wrong result

### ISSUE THREAD

**Issue by MatsIBengtsson** [jborean93/ansible-windows#9]
The code $os_version = [System.Environment]::OSVersion.Version uses a deprecated function in windows 8.1. It returns a value, but thw wrong value (identifies as Windows server 2012).

Changing it to $os_version =(Get-CimInstance Win32_OperatingSystem).version gives the right version.

**Comment by jborean93** [comment]
Thanks, I went a slightly different route as part of https://github.com/jborean93/ansible-windows/pull/10 but it achieves the same results.
